### ISSUE TITLE
title 사진 변경

### ISSUE THREAD

**Issue by smallfish06** [d-ew/Web#1]
![image](https://user-images.githubusercontent.com/37919847/62456312-1b815300-b7b3-11e9-8a76-a5ea7d2abb68.png)
리액트사진!

**Comment by gwuiinKim** [comment]
오키! 근데 사진 뭘로 바꾸지..? ㅋㅋㅋ 우리 로고 나오면 그걸로 바꿔야 하나?

**Comment by smallfish06** [comment]
로고나오면 바꾸면 될듯 여러 이니셜들이나 페이지 하단 표시도 같이
